### ISSUE TITLE
setting communication configuration

### ISSUE THREAD

**Issue by yuniaregiprasasti** [Namoshek/OpenChargeMeteringFormat#64]
Hallo,
I'm new developer for open charge metering format, and I trying to learn ur code to retrieve the data from energy meter that have the ocmf communication, the energy meter have physical communication rj12 to rs485, and it have the configuration (baud rate, parity, id, etc) like modbus configuration. So, my question, Do I need the additional code for this configuration to retrieve the data?

thankyou

**Comment by Namoshek** [comment]
I'm sorry but the communication between the charge point or meter and the backend is out of scope for this library. This project is only about a parser for OCMF packages, not about the transmission of such. In most cases, the OCMF data is transferred from the charge point to a backend using the OCPP protocol or similar.

**Comment by yuniaregiprasasti** [comment]
Hello..
Perhaps, Do you have any knowledge about transmission data using ocmf
protocol?
Because, I cannot found article or anything that explain about ocmf.
I need to connecting the energy meter to the device, but how?

Thank you so much for ur response

**Comment by Namoshek** [comment]
I only know about one use case of OCMF: When a charge point sends transaction data using `StartTransaction` and `StopTransaction` (as well as intermediate `MeterValues`) using the Open Charge Point Protocol (OCPP), it may add OCMF data read from the electricity meter. The result of such a transaction will be a Charge Detail Record (CDR) which may (or may not) contain OCMF data.

In the past, I've been working on backend systems that involve the communication with charge points using OCPP. This protocol is implemented by a compute unit in the charge point. That compute unit _may_ also communicate with an electricity meter that is able to capture OCMF data. I've not been involved in such an implementation though, so I'm afraid I cannot help you with this.
